//! Black-box validation against a DTS frame produced by the
//! `ffmpeg` binary (clean-room: ffmpeg is used only as an opaque
//! generator — its source is not consulted).
//!
//! The fixture is the first 16 bytes (4-byte sync + 12 bytes of
//! header) of a frame generated by:
//!
//! ```text
//!   ffmpeg -f lavfi -i "sine=frequency=440:duration=0.5" \
//!          -ac 2 -ar 48000 -c:a dca -strict experimental \
//!          -b:a 768k -f dts /tmp/test.dts
//! ```
//!
//! `ffprobe` reports the file as 48000 Hz stereo @ 768 kb/s; this
//! test only confirms that the parser ingests a real frame and
//! returns the structural fields we documented. The mapping from
//! `sfreq_index` / `rate_index` / `amode` back to those Hz / bps /
//! channel-count values is the docs-gap the round 1 report calls
//! out — once the tables land in `docs/`, the resolvers can also
//! be checked against `(48000, 768000, 2)` here.

use oxideav_dts::{
    parse_frame_header, parse_frame_header_14bit, unpack_14bit_to_16bit, FourteenBitByteOrder,
    FrameType, LfeMode, SyncWordEncoding, TargetedBitRate,
};

/// 16 bytes captured from a real `ffmpeg -c:a dca -b:a 768k -ar
/// 48000 -ac 2` output (frame 0). 4-byte sync + 12 bytes of header
/// is enough for the round-1 parser to read all 82 header bits.
const FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER: [u8; 16] = [
    0x7f, 0xfe, 0x80, 0x01, 0xfc, 0x3c, 0x3f, 0xf0, 0xb5, 0xe0, 0x01, 0x38, 0x00, 0x03, 0xef, 0x7f,
];

#[test]
fn parses_real_ffmpeg_frame_header() {
    let hdr = parse_frame_header(&FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER)
        .expect("parse should succeed on real DTS frame");
    assert_eq!(hdr.sync_word_encoding, SyncWordEncoding::RawBigEndian);
    assert_eq!(hdr.frame_type, FrameType::Normal);
    // ffmpeg's DCA encoder emits 32 samples per sub-block.
    assert_eq!(hdr.sample_count_per_block, 32);
    // ffmpeg's DCA encoder does NOT set CRC_PRESENT on the frame
    // we sampled (the header CRC field is therefore absent).
    assert!(!hdr.crc_present);
    // Frame size for 768 kb/s @ 48 kHz with 16 blocks: each frame
    // covers 512 samples ≈ 10.667 ms → 1024 bytes.
    assert_eq!(hdr.frame_size_bytes, 1024);
    // 16 sub-blocks of 32 samples each.
    assert_eq!(hdr.blocks_per_frame, 15);

    // The raw indices below are what the parser observed. ffprobe's
    // external read of the same file reports AMODE 2 == stereo,
    // SFREQ 13 == 48 kHz, RATE 15 == 768 kb/s.
    assert_eq!(hdr.amode, 2);
    assert_eq!(hdr.sfreq_index, 13);
    assert_eq!(hdr.rate_index, 15);

    // Round 185: the RATE table (ETSI §5.3.1 Table 5-7) resolves the
    // bitrate. Code 15 (0b01111) → 768 000 bps — cross-validated
    // against ffprobe's external read of this same frame (768 kb/s).
    assert_eq!(hdr.bit_rate_bps(), Some(768_000));
    assert_eq!(hdr.targeted_bit_rate(), TargetedBitRate::Fixed(768_000));
    // Round 202: SFREQ (Table 5-5) / AMODE (Table 5-4) / PCMR
    // (Table 5-17) resolvers now wired up against the staged ETSI
    // PDF. ffprobe reports this fixture as 48 kHz stereo with 16-bit
    // source PCM, which matches the resolver outputs exactly.
    assert_eq!(hdr.sample_rate_hz(), Some(48_000));
    assert_eq!(hdr.channel_count(), Some(2));

    // Round 3: trailing-13-bit field as observed in the real
    // ffmpeg frame. Bytes 9..11 carry 0xE0 0x01 = 1110_0000
    // 0000_0001 → after RATE (which ends at byte-9 bit 2) the 13
    // trailing bits are 00000_0000_0001 (MSB-first), so every flag
    // is zero, ext_descr = 0, LFE code = 0 (no LFE channel — ffmpeg
    // was invoked with -ac 2 stereo), predictor_history = 1.
    assert!(!hdr.downmix);
    assert!(!hdr.dynamic_range);
    assert!(!hdr.time_stamp);
    assert!(!hdr.aux_data);
    assert!(!hdr.hdcd);
    assert_eq!(hdr.ext_descr, 0);
    assert!(!hdr.ext_coding);
    assert!(!hdr.aspf);
    assert_eq!(hdr.lfe, LfeMode::None);
    assert!(!hdr.lfe.is_present());
    assert!(hdr.predictor_history);
    // crc_present was 0 on this fixture, so the optional CRC field
    // is absent and `verify_header_crc` has nothing to verify.
    assert_eq!(hdr.header_crc, None);
    assert_eq!(hdr.verify_header_crc(), None);

    // Round 5: the 16 post-CRC bits in this fixture come from bytes
    // 11..12 = 0x38 0x00 = 0b0011_1000_0000_0000 = 0x3800. Decomposed
    // MSB-first per the wiki:
    //   bit 15 (multirate_inter) = 0
    //   bits 14..11 (version)    = 0b0111 = 7
    //   bits 10..9 (copy_history)= 0b00   = 0
    //   bits 8..6  (pcmr)        = 0b000  = 0
    //   bit 5  (front_sum)       = 0
    //   bit 4  (surround_sum)    = 0
    //   bits 3..0 (dialnorm)     = 0b0000 = 0
    assert!(!hdr.multirate_inter);
    assert_eq!(hdr.version, 7);
    assert_eq!(hdr.copy_history, 0);
    assert_eq!(hdr.source_pcm_resolution_index, 0);
    assert!(!hdr.front_sum);
    assert!(!hdr.surround_sum);
    assert_eq!(hdr.dialog_normalization, 0);
    // Round 202: PCMR (Table 5-17) resolves to 16-bit source PCM
    // for this fixture (PCMR field = 0b000 in the post-CRC window).
    // The DIALNORM-dB resolver still waits on Table 5-20 transcription.
    assert_eq!(hdr.source_pcm_bits_per_sample(), Some(16));
    assert_eq!(hdr.dialog_normalization_db(), None);
}

/// The same `ffmpeg` frame as above, repacked into the 14-bit BE
/// container format. Each 16-bit container carries 14 payload bits
/// (sign-extended into the upper 2). The first six bytes match the
/// wiki's documented 14-bit BE sync `1F FF E8 00 07 F0`; the
/// remaining bytes carry the same payload as the 16-bit-raw frame
/// above, repacked. Round 2's `parse_frame_header_14bit` must
/// recover the identical structural fields the raw-BE parse
/// produces.
const FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER_14BIT_BE: [u8; 20] = [
    0x1f, 0xff, 0xe8, 0x00, 0x07, 0xf0, 0xfc, 0x3f, 0xfc, 0x2d, 0x1e, 0x00, 0x04, 0xe0, 0x00, 0x03,
    0xfb, 0xdf, 0xf0, 0x00,
];

/// LE 14-bit-packed mirror of the same ffmpeg frame.
const FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER_14BIT_LE: [u8; 20] = [
    0xff, 0x1f, 0x00, 0xe8, 0xf0, 0x07, 0x3f, 0xfc, 0x2d, 0xfc, 0x00, 0x1e, 0xe0, 0x04, 0x03, 0x00,
    0xdf, 0xfb, 0x00, 0xf0,
];

#[test]
fn parses_14bit_be_repacked_ffmpeg_frame_header() {
    let hdr = parse_frame_header_14bit(&FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER_14BIT_BE)
        .expect("parse_frame_header_14bit should succeed on the BE-repacked ffmpeg frame");
    assert_eq!(
        hdr.sync_word_encoding,
        SyncWordEncoding::FourteenBitBigEndian,
    );
    assert_eq!(hdr.frame_type, FrameType::Normal);
    assert_eq!(hdr.sample_count_per_block, 32);
    assert!(!hdr.crc_present);
    assert_eq!(hdr.blocks_per_frame, 15);
    assert_eq!(hdr.frame_size_bytes, 1024);
    assert_eq!(hdr.amode, 2);
    assert_eq!(hdr.sfreq_index, 13);
    assert_eq!(hdr.rate_index, 15);
    // Round 185: bitrate resolves identically through the 14-bit-BE
    // container path (RATE 15 → 768 000 bps per Table 5-7).
    assert_eq!(hdr.bit_rate_bps(), Some(768_000));
    assert_eq!(hdr.targeted_bit_rate(), TargetedBitRate::Fixed(768_000));
    // Round 202: SFREQ / AMODE resolvers identical across all three
    // documented encodings (48 kHz stereo from Tables 5-5 / 5-4).
    assert_eq!(hdr.sample_rate_hz(), Some(48_000));
    assert_eq!(hdr.channel_count(), Some(2));
    // Round 3: trailing-field equivalence with the raw-BE parse.
    assert_eq!(hdr.lfe, LfeMode::None);
    assert!(hdr.predictor_history);
    assert_eq!(hdr.header_crc, None);
    // Round 5: post-CRC fields recovered identically through the
    // 14-bit-BE container path.
    assert!(!hdr.multirate_inter);
    assert_eq!(hdr.version, 7);
    assert_eq!(hdr.copy_history, 0);
    assert_eq!(hdr.source_pcm_resolution_index, 0);
    assert!(!hdr.front_sum);
    assert!(!hdr.surround_sum);
    assert_eq!(hdr.dialog_normalization, 0);
}

#[test]
fn parses_14bit_le_repacked_ffmpeg_frame_header() {
    let hdr = parse_frame_header_14bit(&FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER_14BIT_LE)
        .expect("parse_frame_header_14bit should succeed on the LE-repacked ffmpeg frame");
    assert_eq!(
        hdr.sync_word_encoding,
        SyncWordEncoding::FourteenBitLittleEndian,
    );
    assert_eq!(hdr.frame_type, FrameType::Normal);
    assert_eq!(hdr.sample_count_per_block, 32);
    assert!(!hdr.crc_present);
    assert_eq!(hdr.blocks_per_frame, 15);
    assert_eq!(hdr.frame_size_bytes, 1024);
    assert_eq!(hdr.amode, 2);
    assert_eq!(hdr.sfreq_index, 13);
    assert_eq!(hdr.rate_index, 15);
    // Round 185: bitrate resolves identically through the 14-bit-LE
    // container path (RATE 15 → 768 000 bps per Table 5-7).
    assert_eq!(hdr.bit_rate_bps(), Some(768_000));
    assert_eq!(hdr.targeted_bit_rate(), TargetedBitRate::Fixed(768_000));
    // Round 202: SFREQ / AMODE resolvers identical across all three
    // documented encodings (48 kHz stereo).
    assert_eq!(hdr.sample_rate_hz(), Some(48_000));
    assert_eq!(hdr.channel_count(), Some(2));
    // Round 3.
    assert_eq!(hdr.lfe, LfeMode::None);
    assert!(hdr.predictor_history);
    assert_eq!(hdr.header_crc, None);
    // Round 5: post-CRC fields recovered identically through the
    // 14-bit-LE container path.
    assert!(!hdr.multirate_inter);
    assert_eq!(hdr.version, 7);
    assert_eq!(hdr.copy_history, 0);
    assert_eq!(hdr.source_pcm_resolution_index, 0);
    assert!(!hdr.front_sum);
    assert!(!hdr.surround_sum);
    assert_eq!(hdr.dialog_normalization, 0);
}

/// Both 14-bit forms decode to the same logical frame as the
/// 16-bit raw form.
#[test]
fn three_input_encodings_decode_to_identical_header_fields() {
    let raw = parse_frame_header(&FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER).unwrap();
    let be14 =
        parse_frame_header_14bit(&FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER_14BIT_BE).unwrap();
    let le14 =
        parse_frame_header_14bit(&FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER_14BIT_LE).unwrap();
    // Sync-word fields differ by design; the rest must match.
    for (a, b) in [(raw, be14), (raw, le14)] {
        assert_eq!(a.frame_type, b.frame_type);
        assert_eq!(a.sample_count_per_block, b.sample_count_per_block);
        assert_eq!(a.crc_present, b.crc_present);
        assert_eq!(a.blocks_per_frame, b.blocks_per_frame);
        assert_eq!(a.frame_size_bytes, b.frame_size_bytes);
        assert_eq!(a.amode, b.amode);
        assert_eq!(a.sfreq_index, b.sfreq_index);
        assert_eq!(a.rate_index, b.rate_index);
        // Round 3: trailing flags + CRC field must also be
        // bit-equivalent across the three documented encodings.
        assert_eq!(a.downmix, b.downmix);
        assert_eq!(a.dynamic_range, b.dynamic_range);
        assert_eq!(a.time_stamp, b.time_stamp);
        assert_eq!(a.aux_data, b.aux_data);
        assert_eq!(a.hdcd, b.hdcd);
        assert_eq!(a.ext_descr, b.ext_descr);
        assert_eq!(a.ext_coding, b.ext_coding);
        assert_eq!(a.aspf, b.aspf);
        assert_eq!(a.lfe, b.lfe);
        assert_eq!(a.predictor_history, b.predictor_history);
        assert_eq!(a.header_crc, b.header_crc);
        // Round 5: post-CRC fields too.
        assert_eq!(a.multirate_inter, b.multirate_inter);
        assert_eq!(a.version, b.version);
        assert_eq!(a.copy_history, b.copy_history);
        assert_eq!(a.source_pcm_resolution_index, b.source_pcm_resolution_index);
        assert_eq!(a.front_sum, b.front_sum);
        assert_eq!(a.surround_sum, b.surround_sum);
        assert_eq!(a.dialog_normalization, b.dialog_normalization);
    }
}

/// `unpack_14bit_to_16bit` on the 14-bit-BE buffer reproduces the
/// original raw-BE byte sequence as its leading prefix.
#[test]
fn unpacked_be_buffer_prefix_matches_raw_be_header() {
    let unpacked = unpack_14bit_to_16bit(
        &FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER_14BIT_BE,
        FourteenBitByteOrder::BigEndian,
    )
    .unwrap();
    // The raw-BE fixture is the first 16 bytes of the same frame; the
    // 14-bit-packed buffer carries those 16 bytes (= 128 bits) plus a
    // little extra padding. The first 16 bytes of the unpacked output
    // must therefore equal the raw-BE fixture exactly.
    assert_eq!(
        &unpacked[..FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER.len()],
        &FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER,
    );
}
