//! Black-box validation against a DTS frame produced by the
//! `ffmpeg` binary (clean-room: ffmpeg is used only as an opaque
//! generator — its source is not consulted).
//!
//! The fixture is the first 16 bytes (4-byte sync + 12 bytes of
//! header) of a frame generated by:
//!
//! ```text
//!   ffmpeg -f lavfi -i "sine=frequency=440:duration=0.5" \
//!          -ac 2 -ar 48000 -c:a dca -strict experimental \
//!          -b:a 768k -f dts /tmp/test.dts
//! ```
//!
//! `ffprobe` reports the file as 48000 Hz stereo @ 768 kb/s; this
//! test only confirms that the parser ingests a real frame and
//! returns the structural fields we documented. The mapping from
//! `sfreq_index` / `rate_index` / `amode` back to those Hz / bps /
//! channel-count values is the docs-gap the round 1 report calls
//! out — once the tables land in `docs/`, the resolvers can also
//! be checked against `(48000, 768000, 2)` here.

use oxideav_dts::{parse_frame_header, FrameType, SyncWordEncoding};

/// 16 bytes captured from a real `ffmpeg -c:a dca -b:a 768k -ar
/// 48000 -ac 2` output (frame 0). 4-byte sync + 12 bytes of header
/// is enough for the round-1 parser to read all 82 header bits.
const FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER: [u8; 16] = [
    0x7f, 0xfe, 0x80, 0x01, 0xfc, 0x3c, 0x3f, 0xf0, 0xb5, 0xe0, 0x01, 0x38, 0x00, 0x03, 0xef, 0x7f,
];

#[test]
fn parses_real_ffmpeg_frame_header() {
    let hdr = parse_frame_header(&FFMPEG_DTS_48K_STEREO_768K_FRAME0_HEADER)
        .expect("parse should succeed on real DTS frame");
    assert_eq!(hdr.sync_word_encoding, SyncWordEncoding::RawBigEndian);
    assert_eq!(hdr.frame_type, FrameType::Normal);
    // ffmpeg's DCA encoder emits 32 samples per sub-block.
    assert_eq!(hdr.sample_count_per_block, 32);
    // ffmpeg's DCA encoder does NOT set CRC_PRESENT on the frame
    // we sampled (the header CRC field is therefore absent).
    assert!(!hdr.crc_present);
    // Frame size for 768 kb/s @ 48 kHz with 16 blocks: each frame
    // covers 512 samples ≈ 10.667 ms → 1024 bytes.
    assert_eq!(hdr.frame_size_bytes, 1024);
    // 16 sub-blocks of 32 samples each.
    assert_eq!(hdr.blocks_per_frame, 15);

    // The raw indices below are what the parser observed; the
    // semantic mapping (AMODE 2 == stereo, SFREQ 13 == 48 kHz,
    // RATE 15 == 768 kb/s, all per ffprobe's external read of the
    // same file) cannot be asserted yet because the index→value
    // tables are not in `docs/` (see README "Docs gaps").
    assert_eq!(hdr.amode, 2);
    assert_eq!(hdr.sfreq_index, 13);
    assert_eq!(hdr.rate_index, 15);

    // The resolvers must return None until the tables land.
    assert_eq!(hdr.sample_rate_hz(), None);
    assert_eq!(hdr.bit_rate_bps(), None);
    assert_eq!(hdr.channel_count(), None);
}
